lista_preguntas = [
    {'pregunta': '¿Cual es el equipo con mas Champions ?', 'respuesta_1': 'Barcelona', 'respuesta_2': 'Real Madrid', 'respuesta_3': 'Milan', 'respuesta_4': 'Man. United', 'correcta': 2},
    {'pregunta': '¿Que seleccion de futbol gano primer mundial?', 'respuesta_1': 'Uruguay', 'respuesta_2': 'Brasil', 'respuesta_3': 'Alemania', 'respuesta_4': 'Inglaterra', 'correcta': 1},
    {'pregunta': '¿Que jugador es conocido como "La Joya"?', 'respuesta_1': 'Cristiano Ronaldo', 'respuesta_2': 'Lamine Yamal', 'respuesta_3': 'Paulo Dybala', 'respuesta_4': 'Haaland', 'correcta': 3},
    {'pregunta': '¿Quién es el máximo goleador histórico de la Champions?', 'respuesta_1': 'Lionel Messi', 'respuesta_2': 'Cristiano Ronaldo', 'respuesta_3': 'Robert Lew.', 'respuesta_4': 'Kylian Mbappé', 'correcta': 2},
    {'pregunta': '¿En qué país se originó el fútbol?', 'respuesta_1': 'Brasil', 'respuesta_2': 'Inglaterra', 'respuesta_3': 'Italia', 'respuesta_4': 'Alemania', 'correcta': 2},
    {'pregunta': '¿Quién ganó el Mundial de 2022?', 'respuesta_1': 'Francia', 'respuesta_2': 'Argentina', 'respuesta_3': 'Croacia', 'respuesta_4': 'Marruecos', 'correcta': 2},
    {'pregunta': '¿Cuántos mundiales tiene Brasil?', 'respuesta_1': '3', 'respuesta_2': '4', 'respuesta_3': '5', 'respuesta_4': '6', 'correcta': 3},
    {'pregunta': '¿Quién es conocido como "El Fenómeno"?', 'respuesta_1': 'Ronaldinho', 'respuesta_2': 'Neymar', 'respuesta_3': 'Ronaldo Nazário', 'respuesta_4': 'Kaká', 'correcta': 3},
    {'pregunta': '¿Qué equipo ganó la Champions League en 2005?', 'respuesta_1': 'Barcelona', 'respuesta_2': 'Liverpool', 'respuesta_3': 'Milan', 'respuesta_4': 'Juventus', 'correcta': 2},
    {'pregunta': '¿Quién es el capitán de la argentina en 2022?', 'respuesta_1': 'Ángel Di María', 'respuesta_2': 'Lionel Messi', 'respuesta_3': 'Nicolás Otamendi', 'respuesta_4': 'Emiliano Martínez', 'correcta': 2},
    {'pregunta': '¿En qué club jugó Diego Maradona en Italia?', 'respuesta_1': 'Juventus', 'respuesta_2': 'Inter', 'respuesta_3': 'Napoli', 'respuesta_4': 'Milan', 'correcta': 3},
    {'pregunta': '¿Quién tiene más títulos de Liga de España?', 'respuesta_1': 'Barcelona', 'respuesta_2': 'Atlético Madrid', 'respuesta_3': 'Real Madrid', 'respuesta_4': 'Sevilla', 'correcta': 3},
    {'pregunta': '¿Quién marcó el famoso gol con "la mano de Dios"?', 'respuesta_1': 'Cristiano Ronaldo', 'respuesta_2': 'Lionel Messi', 'respuesta_3': 'Diego Maradona', 'respuesta_4': 'Sergio Agüero', 'correcta': 3},
    {'pregunta': '¿Quién fue el máximo goleador del Mundial 2014?', 'respuesta_1': 'Lionel Messi', 'respuesta_2': 'Neymar', 'respuesta_3': 'Thomas Müller', 'respuesta_4': 'James Rodríguez', 'correcta': 4},
    {'pregunta': '¿En qué año se jugó el primer Mundial de fútbol?', 'respuesta_1': '1928', 'respuesta_2': '1930', 'respuesta_3': '1934', 'respuesta_4': '1938', 'correcta': 2},
    {'pregunta': '¿En qué club debutó Lionel Messi?', 'respuesta_1': "Newell's Old Boys", 'respuesta_2': 'River Plate', 'respuesta_3': 'Barcelona', 'respuesta_4': 'Boca Juniors', 'correcta': 3},
    {'pregunta': '¿Cuántas Champions League tiene el AC Milan?', 'respuesta_1': '5', 'respuesta_2': '6', 'respuesta_3': '7', 'respuesta_4': '8', 'correcta': 3},
    {'pregunta': '¿Quién ganó el Balón de Oro en 2021?', 'respuesta_1': 'Cristiano Ronaldo', 'respuesta_2': 'Lionel Messi', 'respuesta_3': 'Lewandowski', 'respuesta_4': 'Jorginho', 'correcta': 2},
    {'pregunta': '¿En qué país nació Kylian Mbappé?', 'respuesta_1': 'España', 'respuesta_2': 'Bélgica', 'respuesta_3': 'Francia', 'respuesta_4': 'Portugal', 'correcta': 3},
    {'pregunta': '¿Qué selección ganó la Eurocopa 2004?', 'respuesta_1': 'Alemania', 'respuesta_2': 'España', 'respuesta_3': 'Grecia', 'respuesta_4': 'Francia', 'correcta': 3},
    {'pregunta': '¿Quién es el entrenador del Manchester City en 2023?', 'respuesta_1': 'José Mourinho', 'respuesta_2': 'Carlo Ancelotti', 'respuesta_3': 'Pep Guardiola', 'respuesta_4': 'Zinedine Zidane', 'correcta': 3},
    {'pregunta': '¿En qué año se fundó el club Boca Juniors?', 'respuesta_1': '1905', 'respuesta_2': '1913', 'respuesta_3': '1920', 'respuesta_4': '1900', 'correcta': 1},
    {'pregunta': '¿Quién ganó la Champions League 2020?', 'respuesta_1': 'PSG', 'respuesta_2': 'Bayern Múnich', 'respuesta_3': 'Liverpool', 'respuesta_4': 'Man. City', 'correcta': 2},
    {'pregunta': '¿Cuál fue el país anfitrión del Mundial 2002?', 'respuesta_1': 'Alemania', 'respuesta_2': 'Corea del Sur y Japón', 'respuesta_3': 'Italia', 'respuesta_4': 'Francia', 'correcta': 2},
    {'pregunta': '¿Quién marcó el gol de la victoria en la final del Mundial 2010?', 'respuesta_1': 'Iniesta', 'respuesta_2': 'Xavi', 'respuesta_3': 'Torres', 'respuesta_4': 'Villa', 'correcta': 1},
    {'pregunta': '¿En qué club jugó Pelé la mayor parte de su carrera?', 'respuesta_1': 'Flamengo', 'respuesta_2': 'Santos', 'respuesta_3': 'Corinthians', 'respuesta_4': 'Vasco da Gama', 'correcta': 2},
    {'pregunta': '¿Qué equipo inglés tiene más títulos de Premier League?', 'respuesta_1': 'Chelsea', 'respuesta_2': 'Arsenal', 'respuesta_3': 'Man. United', 'respuesta_4': 'Liverpool', 'correcta': 3},
    {'pregunta': '¿Cuántos goles marcó Messi en el Mundial de 2022?', 'respuesta_1': '4', 'respuesta_2': '5', 'respuesta_3': '6', 'respuesta_4': '7', 'correcta': 4},
    {'pregunta': '¿Quién ganó la Copa América 2021?', 'respuesta_1': 'Brasil', 'respuesta_2': 'Uruguay', 'respuesta_3': 'Argentina', 'respuesta_4': 'Colombia', 'correcta': 3},
    {'pregunta': '¿Dónde juega actualmente Cristiano Ronaldo (2024)?', 'respuesta_1': 'Man. United', 'respuesta_2': 'Al-Nassr', 'respuesta_3': 'Juventus', 'respuesta_4': 'Real Madrid', 'correcta': 2},
    {'pregunta': '¿Quién es el máximo goleador de la historia de Brasil?', 'respuesta_1': 'Pelé', 'respuesta_2': 'Neymar', 'respuesta_3': 'Zico', 'respuesta_4': 'Ronaldo', 'correcta': 2},
    {'pregunta': '¿Quién ganó la Champions League 2023?', 'respuesta_1': 'Real Madrid', 'respuesta_2': 'Man. City', 'respuesta_3': 'Inter de Milán', 'respuesta_4': 'Napoli', 'correcta': 2},
    {'pregunta': '¿Quién fue el portero de Italia en el Mundial 2006?', 'respuesta_1': 'Buffon', 'respuesta_2': 'Toldo', 'respuesta_3': 'Peruzzi', 'respuesta_4': 'Marchetti', 'correcta': 1},
    {'pregunta': '¿Quién fue el capitán de Alemania en el Mundial 2014?', 'respuesta_1': 'Neuer', 'respuesta_2': 'Khedira', 'respuesta_3': 'Lahm', 'respuesta_4': 'Schweinsteiger', 'correcta': 3},
    {'pregunta': '¿Qué país fue eliminado por Corea del Sur en el Mundial 2018?', 'respuesta_1': 'Alemania', 'respuesta_2': 'España', 'respuesta_3': 'Brasil', 'respuesta_4': 'Portugal', 'correcta': 1},
    {'pregunta': '¿Quién ganó el Mundial de Clubes 2022?', 'respuesta_1': 'Chelsea', 'respuesta_2': 'Flamengo', 'respuesta_3': 'Real Madrid', 'respuesta_4': 'Liverpool', 'correcta': 3},
    {'pregunta': '¿Quién es conocido como "El Apache"?', 'respuesta_1': 'Carlos Tévez', 'respuesta_2': 'Sergio Agüero', 'respuesta_3': 'Gabriel Batistuta', 'respuesta_4': 'Ángel Di María', 'correcta': 1},
    {'pregunta': '¿Qué jugador fue apodado "El Niño"?', 'respuesta_1': 'David Villa', 'respuesta_2': 'Fernando Torres', 'respuesta_3': 'Raúl', 'respuesta_4': 'Isco', 'correcta': 2},
    {'pregunta': '¿Qué selección tiene más títulos de Copa América?', 'respuesta_1': 'Brasil', 'respuesta_2': 'Argentina', 'respuesta_3': 'Uruguay', 'respuesta_4': 'Chile', 'correcta': 3},
    {'pregunta': '¿Quién dirigió a Francia en el Mundial 2018?', 'respuesta_1': 'Zidane', 'respuesta_2': 'Laurent Blanc', 'respuesta_3': 'Deschamps', 'respuesta_4': 'Domenech', 'correcta': 3},
    {'pregunta': '¿En qué país nació Erling Haaland?', 'respuesta_1': 'Suecia', 'respuesta_2': 'Noruega', 'respuesta_3': 'Dinamarca', 'respuesta_4': 'Finlandia', 'correcta': 2},
    {'pregunta': '¿Quién es el máximo goleador de la historia del Barcelona?', 'respuesta_1': 'Luis Suárez', 'respuesta_2': 'Lionel Messi', 'respuesta_3': "Samuel Eto'o", 'respuesta_4': 'Romário', 'correcta': 2},
    {'pregunta': '¿Cuántos Mundiales ganó Italia?', 'respuesta_1': '2', 'respuesta_2': '3', 'respuesta_3': '4', 'respuesta_4': '5', 'correcta': 3},
    {'pregunta': '¿En qué año debutó Messi en la selección argentina?', 'respuesta_1': '2003', 'respuesta_2': '2004', 'respuesta_3': '2005', 'respuesta_4': '2006', 'correcta': 3},
    {'pregunta': '¿Qué equipo ganó la Libertadores 2018?', 'respuesta_1': 'Boca Juniors', 'respuesta_2': 'River Plate', 'respuesta_3': 'Palmeiras', 'respuesta_4': 'Flamengo', 'correcta': 2},
    {'pregunta': '¿Quién es el jugador con más partidos en la historia del fútbol?', 'respuesta_1': 'Cristiano Ronaldo', 'respuesta_2': 'Iker Casillas', 'respuesta_3': 'Messi', 'respuesta_4': 'Sergio Ramos', 'correcta': 1},
    {'pregunta': '¿Quién ganó el Balón de Oro en 2006?', 'respuesta_1': 'Ronaldinho', 'respuesta_2': 'Zidane', 'respuesta_3': 'Fabio Cannavaro', 'respuesta_4': 'Kaká', 'correcta': 3},
    {'pregunta': '¿Quién es el máximo asistidor de la historia del fútbol?', 'respuesta_1': 'Xavi', 'respuesta_2': 'Neymar', 'respuesta_3': 'Messi', 'respuesta_4': 'De Bruyne', 'correcta': 3},
    {'pregunta': '¿Quién fue el técnico de España en el Mundial 2010?', 'respuesta_1': 'Luis Enrique', 'respuesta_2': 'Vicente del Bosque', 'respuesta_3': 'Delgado', 'respuesta_4': 'Moreno', 'correcta': 2},
    {'pregunta': '¿Quién ganó la Eurocopa 2020?', 'respuesta_1': 'Inglaterra', 'respuesta_2': 'Italia', 'respuesta_3': 'España', 'respuesta_4': 'Francia', 'correcta': 2},
    {'pregunta': '¿Quién fue el goleador del Mundial 2010?', 'respuesta_1': 'Villa', 'respuesta_2': 'Forlán', 'respuesta_3': 'Klose', 'respuesta_4': 'Müller', 'correcta': 4},
    {'pregunta': '¿Quién es conocido como "Don Andrés"?', 'respuesta_1': 'Xavi', 'respuesta_2': 'Hernández', 'respuesta_3': 'Iniesta', 'respuesta_4': 'Piqué', 'correcta': 3},
    {'pregunta': '¿En qué club jugó Diego Forlán en España?', 'respuesta_1': 'Real Madrid', 'respuesta_2': 'Sevilla', 'respuesta_3': 'Villarreal', 'respuesta_4': 'Valencia', 'correcta': 3},
    {'pregunta': '¿Qué selección tiene más participaciones en Mundiales?', 'respuesta_1': 'Alemania', 'respuesta_2': 'Brasil', 'respuesta_3': 'Italia', 'respuesta_4': 'Argentina', 'correcta': 2},
    {'pregunta': '¿Quién ganó el Mundial Sub-20 en 2023?', 'respuesta_1': 'Uruguay', 'respuesta_2': 'Italia', 'respuesta_3': 'Argentina', 'respuesta_4': 'Colombia', 'correcta': 1},
    {'pregunta': '¿Quién tiene más títulos de Champions como DT?', 'respuesta_1': 'Zidane', 'respuesta_2': 'Mourinho', 'respuesta_3': 'Guardiola', 'respuesta_4': 'Ancelotti', 'correcta': 4},
    {'pregunta': '¿Qué país fue sede del Mundial 1994?', 'respuesta_1': 'México', 'respuesta_2': 'Alemania', 'respuesta_3': 'Estados Unidos', 'respuesta_4': 'Italia', 'correcta': 3},
    {'pregunta': '¿Quién fue el máximo goleador del Mundial 2002?', 'respuesta_1': 'Klose', 'respuesta_2': 'Ronaldo', 'respuesta_3': 'Figo', 'respuesta_4': 'Rivaldo', 'correcta': 2},
    {'pregunta': '¿En qué equipo jugó Kaká en la Serie A?', 'respuesta_1': 'Roma', 'respuesta_2': 'Milan', 'respuesta_3': 'Inter', 'respuesta_4': 'Juve', 'correcta': 2},
    {'pregunta': '¿Quién ganó el oro olímpico en fútbol masculino en Tokio 2020?', 'respuesta_1': 'Brasil', 'respuesta_2': 'España', 'respuesta_3': 'Alemania', 'respuesta_4': 'México', 'correcta': 1},
    {'pregunta': '¿Quién es conocido como "El Pibe"?', 'respuesta_1': 'Valderrama', 'respuesta_2': 'Zamorano', 'respuesta_3': 'Riquelme', 'respuesta_4': 'Maradona', 'correcta': 1},
    {'pregunta': '¿En qué club juega Jude Bellingham (2024)?', 'respuesta_1': 'Dortmund', 'respuesta_2': 'Real Madrid', 'respuesta_3': 'PSG', 'respuesta_4': 'Liverpool', 'correcta': 2},
    {'pregunta': '¿Qué país ganó la Eurocopa 2016?', 'respuesta_1': 'Francia', 'respuesta_2': 'Portugal', 'respuesta_3': 'Alemania', 'respuesta_4': 'Italia', 'correcta': 2},
    {'pregunta': '¿Qué jugador ganó el Mundial de Clubes 2019?', 'respuesta_1': 'Salah', 'respuesta_2': 'Mane', 'respuesta_3': 'Firmino', 'respuesta_4': 'Roberto Firmino', 'correcta': 1},
    {'pregunta': '¿Cuál es el apodo de la selección de Brasil?', 'respuesta_1': 'La Roja', 'respuesta_2': 'Los Albicelestes', 'respuesta_3': 'La Canarinha', 'respuesta_4': 'Les Bleus', 'correcta': 3},
    {'pregunta': '¿Qué club ganó la Premier League 2015–16?', 'respuesta_1': 'Tottenham', 'respuesta_2': 'Leicester City', 'respuesta_3': 'Chelsea', 'respuesta_4': 'Man. City', 'correcta': 2},
    {'pregunta': '¿Quién fue el entrenador de Inglaterra en el Mundial 2018?', 'respuesta_1': 'Sam Allardyce', 'respuesta_2': 'Gareth Southgate', 'respuesta_3': 'Roy Hodgson', 'respuesta_4': 'Fabio Capello', 'correcta': 2},
    {'pregunta': '¿Qué jugador español ganó el Balón de Oro en 1960?', 'respuesta_1': 'Luis Suárez', 'respuesta_2': ' Di Stéfano', 'respuesta_3': 'Ferenc Puskás', 'respuesta_4': 'Johan Cruyff', 'correcta': 2},
    {'pregunta': '¿En qué estadio juega la selección italiana de fútbol?', 'respuesta_1': 'Wanda Metropolitano', 'respuesta_2': 'Wembley', 'respuesta_3': 'San Siro', 'respuesta_4': 'Estadio Olímpico de Roma', 'correcta': 4},
    {'pregunta': '¿Cuál fue el resultado de la final de la Champions 2019?', 'respuesta_1': '2‑0', 'respuesta_2': '3‑1', 'respuesta_3': '1‑0', 'respuesta_4': '4‑2', 'correcta': 2},
    {'pregunta': '¿Qué club argentino tiene más títulos de Copa Libertadores?', 'respuesta_1': 'River Plate', 'respuesta_2': 'Boca Juniors', 'respuesta_3': 'Independiente', 'respuesta_4': 'Racing', 'correcta': 2},
    {'pregunta': '¿Qué arquero ganó la Bota de Oro del Mundial 2014?', 'respuesta_1': 'No hubo', 'respuesta_2': 'Manuel Neuer', 'respuesta_3': 'David de Gea', 'respuesta_4': 'Keylor Navas', 'correcta': 1},
    {'pregunta': '¿Qué selección llegó a cuartos de final en Mundial 2022?', 'respuesta_1': 'Senegal', 'respuesta_2': 'Ghana', 'respuesta_3': 'Marruecos', 'respuesta_4': 'Nigeria', 'correcta': 3},
    {'pregunta': '¿Quién marcó el gol del título de la Eurocopa 2012?', 'respuesta_1': 'Mario Balotelli', 'respuesta_2': 'Andrés Iniesta', 'respuesta_3': 'Fernando Torres', 'respuesta_4': 'Mario Gomez', 'correcta': 2},
    {'pregunta': '¿Qué club de la MLS ganó más títulos hasta 2024?', 'respuesta_1': 'Los Angeles Galaxy', 'respuesta_2': 'Seattle Sounders', 'respuesta_3': 'Atlanta United', 'respuesta_4': 'New York Red Bulls', 'correcta': 1},
    {'pregunta': '¿Cuál es el nombre del estadio del FC Barcelona?', 'respuesta_1': 'Old Trafford', 'respuesta_2': 'Camp Nou', 'respuesta_3': ' Bernabéu', 'respuesta_4': 'Allianz Arena', 'correcta': 2},
    {'pregunta': '¿Qué seleccionador llevó a Francia al título mundial en 2018?', 'respuesta_1': 'Didier Deschamps', 'respuesta_2': 'Zinedine Zidane', 'respuesta_3': 'Laurent Blanc', 'respuesta_4': 'Aimé Jacquet', 'correcta': 1},
    {'pregunta': '¿En qué año ganó Alemania Oriental su único título de Bundesliga?', 'respuesta_1': '1990', 'respuesta_2': '1991', 'respuesta_3': '1992', 'respuesta_4': '1989', 'correcta': 1},
    {'pregunta': '¿Qué selección ganó el primer Mundial Sub-17?', 'respuesta_1': 'Uruguay', 'respuesta_2': 'Brasil', 'respuesta_3': 'Nigeria', 'respuesta_4': 'Argentina', 'correcta': 2},
    {'pregunta': '¿Quién tiene el récord de más goles en una temporada de la Premier League?', 'respuesta_1': 'Mohamed Salah', 'respuesta_2': 'Cristiano Ronaldo', 'respuesta_3': 'Alan Shearer', 'respuesta_4': 'Andy Cole', 'correcta': 1},
    {'pregunta': '¿Qué selección jugó el famoso "Maracanazo"?', 'respuesta_1': 'Brasil vs Uruguay', 'respuesta_2': 'Argentina vs Alemania', 'respuesta_3': 'Uruguay vs Italia', 'respuesta_4': 'Brasil vs Inglaterra', 'correcta': 1},
    {'pregunta': '¿Quién fue el goleador de la liga española 2019–20?', 'respuesta_1': 'Karim Benzema', 'respuesta_2': 'Luis Suárez', 'respuesta_3': 'Lionel Messi', 'respuesta_4': 'Gerard Moreno', 'correcta': 1},
    {'pregunta': '¿Qué selección ganó la Copa Africana de Naciones 2019?', 'respuesta_1': 'Argelia', 'respuesta_2': 'Senegal', 'respuesta_3': 'Nigeria', 'respuesta_4': 'Camerún', 'correcta': 1},
    {'pregunta': '¿Cuántas veces ganó el Mundial la selección de Italia?', 'respuesta_1': '3', 'respuesta_2': '2', 'respuesta_3': '1', 'respuesta_4': '4', 'correcta': 1},
    {'pregunta': '¿Dónde se jugó la final del Mundial 1990?', 'respuesta_1': 'Roma', 'respuesta_2': 'Milán', 'respuesta_3': 'Roma ', 'respuesta_4': 'Turín', 'correcta': 3},
    {'pregunta': '¿Quién fue el primer jugador africano en ganar el Balón de Oro?', 'respuesta_1': 'Salif Keïta', 'respuesta_2': 'George Weah', 'respuesta_3': 'Samuel Eto’o', 'respuesta_4': 'Didier Drogba', 'correcta': 2},
    {'pregunta': '¿Qué selección ganó la Copa América 2019?', 'respuesta_1': 'Argentina', 'respuesta_2': 'Brasil', 'respuesta_3': 'Chile', 'respuesta_4': 'Uruguay', 'correcta': 2},
    {'pregunta': '¿Quién fue el máximo goleador de la Eurocopa 2020?', 'respuesta_1': 'Cristiano Ronaldo', 'respuesta_2': 'Harry Kane', 'respuesta_3': 'Patrik Schick', 'respuesta_4': 'Kylian Mbappé', 'correcta': 3},
    {'pregunta': '¿Cuál fue el presupuesto más alto de transferencia en 2023?', 'respuesta_1': '120 M EUR', 'respuesta_2': '150 M EUR', 'respuesta_3': '200 M EUR', 'respuesta_4': '180 M EUR', 'correcta': 4},
    {'pregunta': '¿Qué país ganó la Eurocopa 2016?', 'respuesta_1': 'Francia', 'respuesta_2': 'Portugal', 'respuesta_3': 'Alemania', 'respuesta_4': 'Italia', 'correcta': 2},
    {'pregunta': '¿Qué jugador anotó el gol de la victoria en la final de la Euro 2008?', 'respuesta_1': 'Iniesta', 'respuesta_2': 'Xavi', 'respuesta_3': 'Fernando Torres', 'respuesta_4': 'Villa', 'correcta': 3},
    {'pregunta': '¿Qué selección organizó y ganó el Mundial en 1998?', 'respuesta_1': 'Brasil', 'respuesta_2': 'Francia', 'respuesta_3': 'Italia', 'respuesta_4': 'Alemania', 'correcta': 2},
    {'pregunta': '¿Qué club ganó la Champions League en 2012?', 'respuesta_1': 'Chelsea', 'respuesta_2': 'Bayern Múnich', 'respuesta_3': 'Barcelona', 'respuesta_4': 'Inter de Milán', 'correcta': 1},
    {'pregunta': '¿Quién fue el goleador del Mundial 2018?', 'respuesta_1': 'Griezmann', 'respuesta_2': 'Mbappé', 'respuesta_3': 'Harry Kane', 'respuesta_4': 'Lukaku', 'correcta': 3},
    {'pregunta': '¿Qué selección usó una camiseta negra en un Mundial?', 'respuesta_1': 'Senegal', 'respuesta_2': 'Croacia', 'respuesta_3': 'Nueva Zelanda', 'respuesta_4': 'Alemania', 'correcta': 3},
    {'pregunta': '¿Cuál fue el primer club profesional de Cristiano Ronaldo?', 'respuesta_1': 'Sporting CP', 'respuesta_2': 'Porto', 'respuesta_3': 'Man. United', 'respuesta_4': 'Benfica', 'correcta': 1},
    {'pregunta': '¿Qué selección ganó el Mundial Femenino 2019?', 'respuesta_1': 'Países Bajos', 'respuesta_2': 'Estados Unidos', 'respuesta_3': 'Alemania', 'respuesta_4': 'Suecia', 'correcta': 2},
    {'pregunta': '¿Qué equipo fue eliminado en fase de grupos en el Mundial 2002?', 'respuesta_1': 'Brasil', 'respuesta_2': 'Francia', 'respuesta_3': 'Alemania', 'respuesta_4': 'Italia', 'correcta': 2},
    {'pregunta': '¿Cuál es el apodo de la selección de Alemania?', 'respuesta_1': 'Azzurra', 'respuesta_2': 'Mannschaft', 'respuesta_3': 'Les Bleus', 'respuesta_4': 'Charrúas', 'correcta': 2},
    {'pregunta': '¿En qué club europeo jugó Drogba la mayor parte de su carrera?', 'respuesta_1': 'Marsella', 'respuesta_2': 'Chelsea', 'respuesta_3': 'Galatasaray', 'respuesta_4': 'Le Mans', 'correcta': 2},
    {'pregunta': '¿Qué selección ganó la Copa Oro 2021?', 'respuesta_1': 'Estados Unidos', 'respuesta_2': 'México', 'respuesta_3': 'Canadá', 'respuesta_4': 'Costa Rica', 'correcta': 1},
    {'pregunta': '¿Qué jugador hizo un triplete en 6 minutos en la Bundesliga?', 'respuesta_1': 'Erling Haaland', 'respuesta_2': 'Gerd Müller', 'respuesta_3': ' Lewandowski', 'respuesta_4': 'Mario Gómez', 'correcta': 3},
    {'pregunta': '¿En qué estadio se jugó la final del Mundial 2014?', 'respuesta_1': 'Maracaná', 'respuesta_2': 'Arena Corinthians', 'respuesta_3': 'Estadio Nacional', 'respuesta_4': 'Mineirao', 'correcta': 1},
    {'pregunta': '¿Qué selección sudamericana fue semifinalista en el Mundial 2010?', 'respuesta_1': 'Brasil', 'respuesta_2': 'Uruguay', 'respuesta_3': 'Argentina', 'respuesta_4': 'Paraguay', 'correcta': 2},
    {'pregunta': '¿Quién ganó el Balón de Oro en 2007?', 'respuesta_1': 'Messi', 'respuesta_2': 'Cristiano Ronaldo', 'respuesta_3': 'Kaká', 'respuesta_4': 'Ronaldinho', 'correcta': 3},
    {'pregunta': '¿Qué equipo brasileño ganó la Libertadores en 2021?', 'respuesta_1': 'Flamengo', 'respuesta_2': 'Palmeiras', 'respuesta_3': 'Santos', 'respuesta_4': 'Gremio', 'correcta': 2},
    {'pregunta': '¿Qué país ha ganado más veces la Copa de África?', 'respuesta_1': 'Egipto', 'respuesta_2': 'Nigeria', 'respuesta_3': 'Camerún', 'respuesta_4': 'Ghana', 'correcta': 1},
    {'pregunta': '¿Qué club argentino descendió en 2011?', 'respuesta_1': 'Boca Juniors', 'respuesta_2': 'San Lorenzo', 'respuesta_3': 'River Plate', 'respuesta_4': 'Independiente', 'correcta': 3},
    {'pregunta': '¿Qué selección perdió una final por penales en 1994?', 'respuesta_1': 'Italia', 'respuesta_2': 'Alemania', 'respuesta_3': 'Argentina', 'respuesta_4': 'Brasil', 'correcta': 1},
    {'pregunta': '¿Quién fue el máximo goleador de la Copa América 2016?', 'respuesta_1': 'Messi', 'respuesta_2': 'Eduardo Vargas', 'respuesta_3': 'Higuaín', 'respuesta_4': 'Alexis Sánchez', 'correcta': 2},
    {'pregunta': '¿Qué selección usó camiseta rosa en un Mundial?', 'respuesta_1': 'México', 'respuesta_2': 'Senegal', 'respuesta_3': 'Italia', 'respuesta_4': 'Nigeria', 'correcta': 1},
    {'pregunta': '¿Qué portero ganó el premio The Best 2022?', 'respuesta_1': 'Dibu Martínez', 'respuesta_2': 'Courtois', 'respuesta_3': 'Alisson', 'respuesta_4': 'Ederson', 'correcta': 1},
    {'pregunta': '¿Qué selección europea fue subcampeona en la Euro 2004?', 'respuesta_1': 'Grecia', 'respuesta_2': 'Portugal', 'respuesta_3': 'España', 'respuesta_4': 'Italia', 'correcta': 2},
    {'pregunta': '¿Cuál es el apodo de la selección uruguaya?', 'respuesta_1': 'La Celeste', 'respuesta_2': 'La Roja', 'respuesta_3': 'La Tricolor', 'respuesta_4': 'Los Incas', 'correcta': 1},
    {'pregunta': '¿Qué jugador argentino usó el dorsal 10 en el Mundial 1994?', 'respuesta_1': 'Batistuta', 'respuesta_2': 'Redondo', 'respuesta_3': 'Maradona', 'respuesta_4': 'Simeone', 'correcta': 3},
    {'pregunta': '¿Qué equipo europeo tiene más títulos de Europa League?', 'respuesta_1': 'Sevilla', 'respuesta_2': 'Inter', 'respuesta_3': 'Liverpool', 'respuesta_4': 'Atlético de Madrid', 'correcta': 1},
    {'pregunta': '¿Qué jugador marcó el gol más rápido en la historia de los mundiales?', 'respuesta_1': 'Hakan Şükür', 'respuesta_2': 'Mbappé', 'respuesta_3': 'Pelé', 'respuesta_4': 'Lineker', 'correcta': 1},
    {'pregunta': '¿Qué equipo ascendió a la Premier League por primera vez en 2023?', 'respuesta_1': 'Luton Town', 'respuesta_2': 'Leeds United', 'respuesta_3': 'Norwich City', 'respuesta_4': 'Watford', 'correcta': 1},
    {'pregunta': '¿Qué país ganó el Mundial Sub-17 en 2019?', 'respuesta_1': 'Brasil', 'respuesta_2': 'México', 'respuesta_3': 'Francia', 'respuesta_4': 'España', 'correcta': 1},
    {'pregunta': '¿Qué equipo fue campeón de la Bundesliga en 2023?', 'respuesta_1': 'RB Leipzig', 'respuesta_2': 'Borussia Dortmund', 'respuesta_3': 'Bayern Múnich', 'respuesta_4': 'Union Berlin', 'correcta': 3},
    {'pregunta': '¿Qué club africano ha ganado más veces la CAF Champions League?', 'respuesta_1': 'TP Mazembe', 'respuesta_2': 'Al Ahly', 'respuesta_3': 'Zamalek', 'respuesta_4': 'Espérance', 'correcta': 2},
    {'pregunta': '¿Qué jugador brasileño fue apodado "El Emperador"?', 'respuesta_1': 'Ronaldo', 'respuesta_2': 'Adriano', 'respuesta_3': 'Ronaldinho', 'respuesta_4': 'Kaká', 'correcta': 2},
    {'pregunta': '¿Cuál fue el primer club profesional de Lionel Messi?', 'respuesta_1': 'Newell’s', 'respuesta_2': 'Barcelona', 'respuesta_3': 'PSG', 'respuesta_4': 'Ninguno', 'correcta': 2},
    {'pregunta': '¿Qué selección eliminó a Inglaterra en el Mundial 2018?', 'respuesta_1': 'Croacia', 'respuesta_2': 'Francia', 'respuesta_3': 'Bélgica', 'respuesta_4': 'Colombia', 'correcta': 1},
    {'pregunta': '¿Qué futbolista fue goleador de la Copa América 2001?', 'respuesta_1': 'Asprilla', 'respuesta_2': 'Ángel', 'respuesta_3': 'Víctor Aristizábal', 'respuesta_4': 'Valderrama', 'correcta': 3},
    {'pregunta': '¿Cuál fue la primera Copa del Mundo en la que participaron 32 selecciones?', 'respuesta_1': '1994', 'respuesta_2': '1998', 'respuesta_3': '2002', 'respuesta_4': '1990', 'correcta': 2},
    {'pregunta': '¿Qué jugador fue fichado por el PSG desde el Borussia Dortmund en 2017?', 'respuesta_1': 'Haaland', 'respuesta_2': 'Sancho', 'respuesta_3': 'Dembélé', 'respuesta_4': 'Meunier', 'correcta': 3},
    {'pregunta': '¿Qué selección tiene el récord de más goles en una sola Copa del Mundo?', 'respuesta_1': 'Hungría (1954)', 'respuesta_2': 'Brasil (2002)', 'respuesta_3': 'Francia (2018)', 'respuesta_4': 'Alemania (2014)', 'correcta': 1},
    {'pregunta': '¿Quién fue el DT de la selección inglesa en el Mundial 2018?', 'respuesta_1': 'Gareth Southgate', 'respuesta_2': 'Roy Hodgson', 'respuesta_3': 'Steve McClaren', 'respuesta_4': 'Sam Allardyce', 'correcta': 1},
    {'pregunta': '¿Qué jugador africano ganó el Balón de Oro en 1995?', 'respuesta_1': 'Didier Drogba', 'respuesta_2': 'George Weah', 'respuesta_3': 'Samuel Eto’o', 'respuesta_4': 'Yaya Touré', 'correcta': 2},
    {'pregunta': '¿Qué equipo ganó la Copa Libertadores en 2012?', 'respuesta_1': 'Boca Juniors', 'respuesta_2': 'Santos', 'respuesta_3': 'Corinthians', 'respuesta_4': 'Fluminense', 'correcta': 3},
    {'pregunta': '¿Quién marcó el gol de oro en la Euro 2000?', 'respuesta_1': 'Zidane', 'respuesta_2': 'Wiltord', 'respuesta_3': 'Trezeguet', 'respuesta_4': 'Henry', 'correcta': 3},
    {'pregunta': '¿Qué equipo ganó el primer Mundial de Clubes (2000)?', 'respuesta_1': 'Corinthians', 'respuesta_2': 'Vasco da Gama', 'respuesta_3': 'Real Madrid', 'respuesta_4': 'Boca Juniors', 'correcta': 1},
    {'pregunta': '¿Cuál fue el primer club en ganar un triplete europeo?', 'respuesta_1': 'Barcelona', 'respuesta_2': 'Man. United', 'respuesta_3': 'Inter de Milán', 'respuesta_4': 'Celtic FC', 'correcta': 4},
    {'pregunta': '¿En qué año se fundó el FC Barcelona?', 'respuesta_1': '1899', 'respuesta_2': '1905', 'respuesta_3': '1910', 'respuesta_4': '1888', 'correcta': 1},
    {'pregunta': '¿Qué club italiano ganó el triplete en 2010?', 'respuesta_1': 'Juventus', 'respuesta_2': 'AC Milan', 'respuesta_3': 'Inter de Milán', 'respuesta_4': 'Napoli', 'correcta': 3},
    {'pregunta': '¿Qué selección jugó la final del Mundial 2018 por primera vez?', 'respuesta_1': 'Croacia', 'respuesta_2': 'Bélgica', 'respuesta_3': 'Uruguay', 'respuesta_4': 'Países Bajos', 'correcta': 1},
    {'pregunta': '¿Qué delantero sueco jugó en PSG, Milan y Manchester United?', 'respuesta_1': 'Henrik Larsson', 'respuesta_2': 'Zlatan Ibrahimović', 'respuesta_3': 'Kulusevski', 'respuesta_4': 'Isak', 'correcta': 2},
    {'pregunta': '¿Qué selección ganó la Copa Confederaciones 2013?', 'respuesta_1': 'Brasil', 'respuesta_2': 'España', 'respuesta_3': 'Italia', 'respuesta_4': 'Uruguay', 'correcta': 1},
    {'pregunta': '¿Quién es el máximo goleador de la historia del PSG?', 'respuesta_1': 'Cavani', 'respuesta_2': 'Mbappé', 'respuesta_3': 'Neymar', 'respuesta_4': 'Ibrahimović', 'correcta': 2},
    {'pregunta': '¿Quién dirigió al Chelsea en la Champions 2021?', 'respuesta_1': 'Lampard', 'respuesta_2': 'Sarri', 'respuesta_3': 'Tuchel', 'respuesta_4': 'Conte', 'correcta': 3},
    {'pregunta': '¿Qué club español ganó la Europa League 2021?', 'respuesta_1': 'Sevilla', 'respuesta_2': 'Villarreal', 'respuesta_3': 'Atlético Madrid', 'respuesta_4': 'Real Sociedad', 'correcta': 2},
    {'pregunta': '¿Quién fue el máximo goleador de la Serie A 2020-21?', 'respuesta_1': 'Cristiano Ronaldo', 'respuesta_2': 'Lukaku', 'respuesta_3': 'Immobile', 'respuesta_4': 'Zlatan', 'correcta': 1},
    {'pregunta': '¿En qué equipo jugó Drogba en Turquía?', 'respuesta_1': 'Besiktas', 'respuesta_2': 'Galatasaray', 'respuesta_3': 'Fenerbahce', 'respuesta_4': 'Trabzonspor', 'correcta': 2},
    {'pregunta': '¿Quién ganó el Mundial Femenino 2015?', 'respuesta_1': 'Japón', 'respuesta_2': 'Alemania', 'respuesta_3': 'Estados Unidos', 'respuesta_4': 'Suecia', 'correcta': 3},
    {'pregunta': '¿Quién marcó el gol de la victoria en la final de Champions 2014?', 'respuesta_1': 'Cristiano Ronaldo', 'respuesta_2': 'Bale', 'respuesta_3': 'Ramos', 'respuesta_4': 'Di María', 'correcta': 2},
    {'pregunta': '¿En qué club debutó profesionalmente Neymar?', 'respuesta_1': 'Santos', 'respuesta_2': 'Barcelona', 'respuesta_3': 'PSG', 'respuesta_4': 'Flamengo', 'correcta': 1},
    {'pregunta': '¿Qué selección ganó la Copa América 2015?', 'respuesta_1': 'Argentina', 'respuesta_2': 'Chile', 'respuesta_3': 'Brasil', 'respuesta_4': 'Uruguay', 'correcta': 2},
    {'pregunta': '¿Quién fue el máximo goleador de la Bundesliga 2020-21?', 'respuesta_1': 'Haaland', 'respuesta_2': 'Lewandowski', 'respuesta_3': 'Müller', 'respuesta_4': 'Andre Silva', 'correcta': 2},
    {'pregunta': '¿Qué club ganó la Europa League 2020?', 'respuesta_1': 'Sevilla', 'respuesta_2': 'Inter', 'respuesta_3': 'Man. United', 'respuesta_4': 'Arsenal', 'correcta': 1},
    {'pregunta': '¿Quién fue elegido mejor jugador joven del Mundial 2014?', 'respuesta_1': 'Pogba', 'respuesta_2': 'Mbappé', 'respuesta_3': 'James Rodríguez', 'respuesta_4': 'Gotze', 'correcta': 1},
]

